### ISSUE TITLE
Is related to FastSAM ?

### ISSUE THREAD

**Issue by mahimairaja** [autodistill/autodistill-yolov8#2]
Asking out of curiosity. Since the the framework is named with yolov8, by any chance is this work related to FastSAM?

**Comment by yeldarby** [comment]
It is but only in a parallel development type of way. FastSAM trains YOLOv8 on the classless output of SAM to mimic SAM as a generic segmentation model. Autodistill is used to label data specifically for specific classes/use-cases.
